name: ifcb-utopia
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.9, <4.0
  - jupyter
  - ipykernel
  - streamlit==1.29
  - numpy>=1.2
  - pandas>=1.4
  - scikit-learn>=1.2
  - matplotlib>=3.5
  - plotly
  - imageio
  - tensorflow==2.13.1
  - pip
  - pip:
      - tqdm
      - pylint
      - modAL
      - azure-storage-blob
      - azure-mgmt-compute>=30.5.0
      - azure-identity
      - azure-mgmt-storage>=21.1.0
      - azure-common>=1.1.28
      - azure-core>=1.28.1
      - azure-mgmt-core>=1.4.0
      - opencv-python
      - streamlit_option_menu
      - pymssql>=2.2
      - umap-learn
      - utopia_pipeline_tools>=0.3.25
      - marimo
      - seaborn
      - ipython